#!/bin/bash

EMAIL=$(git config --get user.email)

function errormsg {
    cat <<EOF
###############
# WRONG EMAIL #
###############

Use a @nicta.com.au email
EOF
    exit 1
}

if $(git remote -v | grep -q nicta.com.au)
then
    [[ $EMAIL =~ .*@data61.csiro.au ]] || errormsg
fi
